image:
  name: docker:stable
services:
  - docker:dind

stages:
  - build
  - deploy

build-image:
  stage: build
  tags:
  - docker
  script:
    - docker build --build-arg ENV=prod -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH

deploy-stag:
  stage: deploy
  cache:
    untracked: true
  image: alpine
  script:
    - echo "Deploy Başarılı"
  when: manual
